---
  - name: Create pyenv
    command: '{{ ansible_env.HOME }}/dotfiles/scripts/install_pyenv.sh'
    args:
      creates: '{{ ansible_env.HOME }}/.pyenv/bin/pyenv'

  - name: Init vim pathogen
    command: '{{ ansible_env.HOME }}/dotfiles/scripts/init_vim_pathogen.sh'
    args:
      creates: '{{ ansible_env.HOME }}/.vim/autoload/pathogen.vim'

  - name: Disable web search
    command: '{{ ansible_env.HOME }}/dotfiles/scripts/disable_web_search.sh'
    changed_when: false

  - name: Setup cron
    command: '{{ ansible_env.HOME }}/dotfiles/scripts/setup_cron.sh'
    changed_when: false
