- hosts: localhost
  tasks:
    # install packages
    - include_tasks: tasks/packages/core.yml
    - include_tasks: tasks/packages/graphical.yml
    - include_tasks: tasks/packages/web.yml
    # Install snap packages
    - include_tasks: tasks/packages/snap.yml
    # Install pyenv requirements
    - include_tasks: tasks/packages/pyenv.yml
    # symlink dotfiles
    - include_tasks: tasks/dotfiles/core.yml
    # launch scripts
    - include_tasks: tasks/scripts/main.yml
