onboarding = false

[ui]
status_indicators = "symbols"
tab_bar_position = "bottom"
sidebar_collapsed_mode = "hidden"
pane_gaps = false
pane_outer_borders = false
pane_scrollbars = false

[theme]
name = "terminal"
auto_switch = false

[keys]
split_vertical = 'prefix+%'
split_horizontal = 'prefix+"'
cycle_pane_next = "prefix+o"
open_notification_target = "prefix+shift+o"
