---
- name: Install libraries using APT
  apt: name={{ item }} state=latest
  become: yes
  become_method: sudo
  with_items:
    - chromium-browser
    - curl
    - epiphany-browser
    - filezilla
    - irssi
    - lynx
    - mailnag
    - openssh-client
    - openssh-server
    - privoxy
    - sshfs
    - tor
